language: elixir

elixir: '1.5'
otp_release: '19.0'

script:
  # This is basically `mix test` with coverage enabled.
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
